export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";

export const DELETE_ITEM = "DELETE_ITEM";

export const DUPLICATE_ITEM = "DUPLICATE_ITEM";

export const SAVE_EDITED_ITEM = "SAVE_EDITED_ITEM";